"""add unique to user email - add password hash to users

Revision ID: cb9b9a891a5a
Revises: 143191742dff
Create Date: 2024-03-24 19:25:41.307142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9b9a891a5a'
down_revision = '143191742dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.create_unique_constraint("unq_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("unq_email", type_='unique')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
